- name: Ensure remote media dir exists
  file:
    path: "{{remote_media_dir}}"
    state: directory
    owner: "{{ansible_ssh_user}}"
  sudo: yes

- name: Ensure /etc/systemd/system dir exists
  file:
    path: /etc/systemd/system
    state: directory
  sudo: yes

- name: Copy evercam_media service
  sudo: yes
  template:
    src: evercam_media.service.j2
    dest: /etc/systemd/system/evercam_media.service
    owner: root
    group: root
    mode: 0755

- name: Enable the evercam_media service
  shell: systemctl enable evercam_media.service
  sudo: yes
  failed_when: False
